/* Generated by tools/firmware_build_info.py. */
#ifndef FIRMWARE_BUILD_INFO_H
#define FIRMWARE_BUILD_INFO_H
#define FIRMWARE_SOURCE_SHA256 "6fdda77eb9f44f4551dc0479842271cbf83df257fcc5906063a882daa289a309"
#define FIRMWARE_CONFIG_SHA256 "a3be40b6d25e961d3ad629bf74e72e8a4c8335a034e8354dd236fbe9d63cf35e"
#define FIRMWARE_BUILD_JSON "{\"base_commit\":\"2eddd1b22335635b92b9e1ba622bed5844aa53e2\",\"dirty_at_generation\":true,\"source_sha256\":\"6fdda77eb9f44f4551dc0479842271cbf83df257fcc5906063a882daa289a309\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define FIRMWARE_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
