/* Generated by tools/firmware_build_info.py. */
#ifndef FIRMWARE_BUILD_INFO_H
#define FIRMWARE_BUILD_INFO_H
#define FIRMWARE_SOURCE_SHA256 "53eeef286e621d96ed6ab8ee4cbe45e4818c9440c453c12511b5319d743b2dde"
#define FIRMWARE_CONFIG_SHA256 "eaf3571ae90684cbe384030e1afa03e22c5afb26cbb10f51e0bbe92cb2abd501"
#define FIRMWARE_BUILD_JSON "{\"base_commit\":\"ac789c2313792b18f6665cdf20d46832165a0f44\",\"dirty_at_generation\":true,\"source_sha256\":\"53eeef286e621d96ed6ab8ee4cbe45e4818c9440c453c12511b5319d743b2dde\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define FIRMWARE_MODEL_JSON "{\"name\":\"model_15000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"dca19cdb9c3745a6133481ab657e7d4b\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
