/* Generated by tools/firmware_build_info.py. */
#ifndef FIRMWARE_BUILD_INFO_H
#define FIRMWARE_BUILD_INFO_H
#define FIRMWARE_SOURCE_SHA256 "d0fcba412487cebd449ba7306815143f63bdec31e691c278cee0abe733aa78db"
#define FIRMWARE_CONFIG_SHA256 "ccf62adbd1a21acb6fc966add18baf82badf709695e28c7192b9c86e0ae0f143"
#define FIRMWARE_BUILD_JSON "{\"base_commit\":\"fd3ec4f13e4b3776643d5fc0f71cc970966a58d3\",\"dirty_at_generation\":true,\"source_sha256\":\"d0fcba412487cebd449ba7306815143f63bdec31e691c278cee0abe733aa78db\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define FIRMWARE_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
