/* Generated by tools/s2r_build_info.py. */
#ifndef S2R_BUILD_INFO_H
#define S2R_BUILD_INFO_H
#define S2R_SOURCE_SHA256 "9bae08c07682c1e46c3f44dcaedd2ea7e58516f532e1fe3033092cba9f174c23"
#define S2R_CONFIG_SHA256 "f7bca5f1ff91d7ca02f2218e4ad5f679ca88bd452d0de0638846aba895337446"
#define S2R_BUILD_JSON "{\"base_commit\":\"38789159e6a1a103adfa25e7e6392b153d1eeaa3\",\"dirty_at_generation\":true,\"source_sha256\":\"9bae08c07682c1e46c3f44dcaedd2ea7e58516f532e1fe3033092cba9f174c23\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define S2R_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
