/* Generated by tools/s2r_build_info.py. */
#ifndef S2R_BUILD_INFO_H
#define S2R_BUILD_INFO_H
#define S2R_SOURCE_SHA256 "5911bf8bb347716fe90285aaa2154eb53d46a66064f6acc793161307bed8cec6"
#define S2R_CONFIG_SHA256 "70059618c025373eeb25e73ccdef33edba92fab1ceaf95c3c705310f7be05a83"
#define S2R_BUILD_JSON "{\"base_commit\":\"237c548dfd9b91d5fc150b7b586daefeae42dffc\",\"dirty_at_generation\":true,\"source_sha256\":\"5911bf8bb347716fe90285aaa2154eb53d46a66064f6acc793161307bed8cec6\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define S2R_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
