/* Generated by tools/s2r_build_info.py. */
#ifndef S2R_BUILD_INFO_H
#define S2R_BUILD_INFO_H
#define S2R_SOURCE_SHA256 "bfdbcc49fced10bdb1530cbda384ec57951ebef17bf7878c7f4831e95c7d47c1"
#define S2R_CONFIG_SHA256 "64e311afec17aca788496f564d9167f633deb9f836093935efb5f133dbda2315"
#define S2R_BUILD_JSON "{\"base_commit\":\"5375e390ff343d0050926f528f2c84b1b6e4dc62\",\"dirty_at_generation\":true,\"source_sha256\":\"bfdbcc49fced10bdb1530cbda384ec57951ebef17bf7878c7f4831e95c7d47c1\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define S2R_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
